# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Chambers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chambers
  pod 'FBSDKLoginKit'
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'GoogleSignIn'
  pod 'Alamofire'
  pod 'CryptoSwift', '~> 1.0'
  pod 'AesGcm'

  target 'ChambersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
