# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Chambers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chambers
  pod 'FBSDKLoginKit'
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'GoogleSignIn'
  pod 'Alamofire'
  pod 'CryptoSwift', '~> 1.0'
  pod 'AesGcm'
  pod 'Amplify'
  pod 'Amplify/Tools'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AWSMobileClient'
  pod 'AWSPinpoint'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'lottie-ios'
 

  target 'ChambersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
